### PR TITLE
Added two new health visualizations.

### PR DESCRIPTION
**Pull request by ericbenwa**

### CODE REVIEW

**Comment by craigmcginley** [comment]
Deploy preview for *loving-austin-5f2eff* ready!

Built with commit fbab8800c3060f3d058298f44ed94176da14d68a

https://deploy-preview-220--loving-austin-5f2eff.netlify.com

**Comment by craigmcginley** [comment]
Also addresses #219

**Comment by craigmcginley** [comment]
Is "Insuring" in the title a play on "ensuring"? jw

**Comment by ericbenwa** [comment]
That's how I took it.
Too cute?

**Comment by craigmcginley** [comment]
Nah

**Pull request merged**
